### ISSUE TITLE
Loading constants using the li instruction

### ISSUE THREAD

**Issue by iamkarthikbk** [VIshweswaranK/Caches#1]
`li` does not take such large constants, the immediate field is only 12 bits long, even in `lui` it is only 20 bits long.
Fix this.

How to load a 64bit constant into a register? The number I want to load is in my head, so it has to be an immediate, right?
We tried these three ways:
 
1) lui, addi, slli, lui, addi (but we are confused because we can't use a second lui)
2) loading the higher 32 bits of the number into the bottom 32 bits, then shifting left by 32 bits and loading the bottom 32 bits (but we're not sure how to do this) https://stackoverflow.com/a/68309378/13777015
3) lui 16bits, slli 8 bits, addi 8 bits, slli 8bits, so on till 64bits are stored. (We think this might work, but is this the best way?)

**Comment by VIshweswaranK** [comment]
Turns out that `li` is a pseudo op that is capable of loading 64bit values. It internally breks down into other instructions to achieve this. Hence this issue can be closed.
